version: '3'
services:
  service1:
    image: demo-jaeger_s1:1.0
    container_name: service1
    environment:
      - "JAEGER_AGENT_HOST=jaeger"
      - "JAEGER_SERVICE_NAME=service1"
    ports:
      - "8080:8080"
    depends_on:
      - "jaeger"
  service2:
    image: demo-jaeger_s2:1.0
    container_name: service2
    environment:
      - "JAEGER_AGENT_HOST=jaeger"
      - "JAEGER_SERVICE_NAME=service2"
    depends_on:
      - "jaeger"
  jaeger:
    image: jaegertracing/all-in-one:1.26
    container_name: jaeger
    environment:
      - COLLECTOR_ZIPKIN_HTTP_PORT=9411
    ports:
      - "16686:16686"
